// Generated by CoffeeScript 1.9.2
(function() {
  var findParentDir, fs, path;

  fs = require('fs');

  path = require('path');

  findParentDir = require('find-parent-dir');

  module.exports = function(fileName) {
    var dir, err;
    try {
      dir = findParentDir.sync(process.cwd(), fileName);
      console.log(dir);
      return JSON.parse(fs.readFileSync(path.join(dir, fileName), 'utf8'));
    } catch (_error) {
      err = _error;
      console.log(err.message);
      return {};
    }
  };

  console.log(module.exports('apps-config.json'));

}).call(this);
